language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: VuzV2ubxnh5xvdrOsBdqaOJ9o6RS9kj5rif39c2AGgLpwPWmRDWXcsURrqeeGVMB4HsuxBKe8xHL8MIbgZqe67bSDBEDvUFa6+jxUuPNUUHxheqI2B/pGXVUdPiu/5y/lktAO60+/X/hn6GXlQVy0Nha0hf0I2OKLfr+ycTmj+4gWYMcLOrPv/Y/F5uudbZqtsviBVgVVnrsT/W2gA+Dh2OlCEHjw3b/KZR5CNnWq4gUPkw2gmArxD/Pa1lZcLTa20QYUExphj42y0RUEx0J/1a0OA42y0TuQ3C8EdyMdYHH8B+NPyIwetiiukaMP7e3ne9gkpJsQEAD/mVVBMjbLWp3NiodePOPIXwSF14/WpMp0S4luL37mArfeiVIoPcNoLtdRPbF56BRSwkvLy7NG7uv07/3znCjwqkUJ2PTYbkgf86YVdU4kqBtVEd53Xmh+wkWGqQ63QNR2EpyoyxT5ExYivXfl8ukjyO0LF/qHb1o/b5BDnfiY4Y4PQS3qthnHdMj62i23v3WNz26oJ2Ya0FHyeILmTaIl3MTMFXV2sLQ78y5W29AxzS7xCNV/Gwue1SgDwjm2gBsCHovTZ2/ROGx0HsPa4Lygx0vEBDhqRYJn0ngGlflSFTgZ3v85Ikfj/m7tjAzHT0MMeEA4kRR/LpXpf7scgK5Icr6iFZnlfg=
  app: guarded-dusk-24354
  on:
    all_branches: 'true'
    repo: P3TeamTwo/p3
  skip_cleanup: 'true'
script:
- echo "skipping tests"
